// A compact data structure to hold all info efficiently
// Format: 
// [Country, [Cities], Region, Population, Currency, Language, Fun Fact, ISO_Code, Main_Export, Flag]

const rawCountryData = [
  ['Afghanistan', ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'], 'Asia', '41 million', 'Afghan afghani', 'Pashto, Dari', 'It is home to the Hindu Kush mountain range.', 'AFG', 'Fruits/Nuts', '🇦🇫'],
  ['Albania', ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier'], 'Europe', '2.8 million', 'Albanian lek', 'Albanian', 'It has hundreds of thousands of concrete bunkers from the communist era.', 'ALB', 'Footwear', '🇦🇱'],
  ['Algeria', ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'], 'Africa', '45 million', 'Algerian dinar', 'Arabic, Berber', 'It is the largest country in Africa by land area.', 'DZA', 'Petroleum/Gas', '🇩🇿'],
  ['American Samoa', ['Pago Pago', 'Tafuna', 'Leone', 'Faleniu'], 'Oceania', '44,000', 'US Dollar', 'English, Samoan', 'It is the only US territory located south of the equator.', 'ASM', 'Canned Tuna', '🇦🇸'],
  ['Andorra', ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Sant Julià de Lòria'], 'Europe', '79,000', 'Euro', 'Catalan', 'It is a co-principality headed by the Bishop of Urgell and the President of France.', 'AND', 'Tobacco', '🇦🇩'],
  ['Angola', ['Luanda', 'Huambo', 'Lobito', 'Lubango', 'Cabinda'], 'Africa', '35 million', 'Angolan kwanza', 'Portuguese', 'It has the giant sable antelope, which was thought to be extinct.', 'AGO', 'Crude Oil', '🇦🇴'],
  ['Anguilla', ['The Valley', 'Blowing Point', 'Sandy Ground'], 'North America', '15,000', 'East Caribbean dollar', 'English', 'It is known for its spectacular coral reefs and beaches.', 'AIA', 'Lobster', '🇦🇮'],
  ['Antarctica', ['McMurdo Station', 'Palmer Station', 'Amundsen-Scott'], 'Antarctica', '0 (varies)', 'None', 'None', 'It holds about 90% of the world\'s fresh water (as ice).', 'ATA', 'Ice/Science', '🇦🇶'],
  ['Antigua and Barbuda', ['St. John\'s', 'All Saints', 'Liberta', 'Potters Village'], 'North America', '99,000', 'East Caribbean dollar', 'English', 'It has a beach for every day of the year (365 beaches).', 'ATG', 'Tourism', '🇦🇬'],
  ['Argentina', ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata'], 'South America', '46 million', 'Argentine peso', 'Spanish', 'It is the birthplace of the tango dance.', 'ARG', 'Soybeans', '🇦🇷'],
  ['Armenia', ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'], 'Asia', '2.8 million', 'Armenian dram', 'Armenian', 'It was the first country to adopt Christianity as its official religion.', 'ARM', 'Copper Ore', '🇦🇲'],
  ['Aruba', ['Oranjestad', 'San Nicolas', 'Noord', 'Santa Cruz'], 'South America', '106,000', 'Aruban florin', 'Dutch, Papiamento', 'It is part of the Kingdom of the Netherlands but located in the Caribbean.', 'ABW', 'Refined Petroleum', '🇦🇼'],
  ['Australia', ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra'], 'Oceania', '26 million', 'Australian dollar', 'English', 'It is the only country that is also a continent.', 'AUS', 'Iron Ore', '🇦🇺'],
  ['Austria', ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'], 'Europe', '9 million', 'Euro', 'German', 'It is the birthplace of Mozart and home to the Alps.', 'AUT', 'Machinery', '🇦🇹'],
  ['Azerbaijan', ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'], 'Asia', '10 million', 'Azerbaijani manat', 'Azerbaijani', 'It is known as the "Land of Fire" due to natural gas flares.', 'AZE', 'Crude Oil', '🇦🇿'],
  ['Bahamas', ['Nassau', 'Freeport', 'West End', 'Coopers Town'], 'North America', '400,000', 'Bahamian dollar', 'English', 'It consists of over 700 islands and cays.', 'BHS', 'Tourism', '🇧🇸'],
  ['Bahrain', ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'], 'Asia', '1.5 million', 'Bahraini dinar', 'Arabic', 'It was the site of the ancient Dilmun civilization.', 'BHR', 'Refined Petroleum', '🇧🇭'],
  ['Bangladesh', ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'], 'Asia', '171 million', 'Bangladeshi taka', 'Bengali', 'It has the longest natural sea beach in the world (Cox\'s Bazar).', 'BGD', 'Textiles', '🇧🇩'],
  ['Barbados', ['Bridgetown', 'Speightstown', 'Oistins', 'Holetown'], 'North America', '281,000', 'Barbadian dollar', 'English', 'It is the easternmost island in the Caribbean.', 'BRB', 'Hard Liquor', '🇧🇧'],
  ['Belarus', ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk'], 'Europe', '9.2 million', 'Belarusian ruble', 'Belarusian, Russian', 'About 40% of its territory is covered by forests.', 'BLR', 'Potash Fertilizers', '🇧🇾'],
  ['Belgium', ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège'], 'Europe', '11.6 million', 'Euro', 'Dutch, French, German', 'It is world-famous for its chocolate and waffles.', 'BEL', 'Chemicals', '🇧🇪'],
  ['Belize', ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk Town'], 'North America', '405,000', 'Belize dollar', 'English', 'It has the second largest barrier reef in the world.', 'BLZ', 'Sugar', '🇧🇿'],
  ['Benin', ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou'], 'Africa', '13 million', 'West African CFA franc', 'French', 'It is the birthplace of the Vodun (Voodoo) religion.', 'BEN', 'Cotton', '🇧🇯'],
  ['Bermuda', ['Hamilton', 'St. George\'s', 'Somerset Village'], 'North America', '64,000', 'Bermudian dollar', 'English', 'It is famous for the mysterious "Bermuda Triangle" legend.', 'BMU', 'Financial Services', '🇧🇲'],
  ['Bhutan', ['Thimphu', 'Phuntsholing', 'Paro', 'Gelephu'], 'Asia', '787,000', 'Ngultrum', 'Dzongkha', 'It measures "Gross National Happiness" instead of GDP.', 'BTN', 'Hydroelectricity', '🇧🇹'],
  ['Bolivia', ['Santa Cruz de la Sierra', 'El Alto', 'La Paz', 'Cochabamba', 'Sucre'], 'South America', '12 million', 'Boliviano', 'Spanish, Quechua, Aymara', 'It is home to the world\'s largest salt flat, Salar de Uyuni.', 'BOL', 'Natural Gas', '🇧🇴'],
  ['Bosnia and Herzegovina', ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'], 'Europe', '3.2 million', 'Convertible mark', 'Bosnian, Croatian, Serbian', 'It is nicknamed the "Heart Shaped Land" due to its shape.', 'BIH', 'Metals', '🇧🇦'],
  ['Botswana', ['Gaborone', 'Francistown', 'Molepolole', 'Maun'], 'Africa', '2.6 million', 'Pula', 'English, Tswana', 'It is home to the world\'s largest concentration of elephants.', 'BWA', 'Diamonds', '🇧🇼'],
  ['Bouvet Island', [], 'Antarctica', '0', 'Norwegian krone', 'Norwegian', 'It is the most remote island in the world.', 'BVT', 'None', '🇧🇻'],
  ['Brazil', ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza'], 'South America', '215 million', 'Brazilian real', 'Portuguese', 'It contains the majority of the Amazon Rainforest.', 'BRA', 'Soybeans', '🇧🇷'],
  ['British Indian Ocean Territory', ['Diego Garcia'], 'Asia', '3,000', 'US Dollar', 'English', 'It serves primarily as a military base.', 'IOT', 'Military', '🇮🇴'],
  ['Brunei Darussalam', ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'], 'Asia', '450,000', 'Brunei dollar', 'Malay', 'It is an absolute monarchy ruled by a Sultan.', 'BRN', 'Crude Oil', '🇧🇳'],
  ['Bulgaria', ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'], 'Europe', '6.5 million', 'Bulgarian lev', 'Bulgarian', 'It produces a significant portion of the world\'s rose oil.', 'BGR', 'Refined Copper', '🇧🇬'],
  ['Burkina Faso', ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'], 'Africa', '22 million', 'West African CFA franc', 'French', 'Its name means "Land of Incorruptible People".', 'BFA', 'Gold', '🇧🇫'],
  ['Burundi', ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi'], 'Africa', '13 million', 'Burundian franc', 'Kirundi, French', 'It is known for its drumming tradition, the Royal Drummers.', 'BDI', 'Coffee', '🇧🇮'],
  ['Cabo Verde', ['Praia', 'Mindelo', 'Espargos', 'Assomada'], 'Africa', '598,000', 'Cape Verdean escudo', 'Portuguese', 'It is an archipelago of 10 volcanic islands.', 'CPV', 'Fish', '🇨🇻'],
  ['Cambodia', ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'], 'Asia', '16.7 million', 'Riel', 'Khmer', 'It is home to Angkor Wat, the largest religious monument in the world.', 'KHM', 'Textiles', '🇰🇭'],
  ['Cameroon', ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam'], 'Africa', '28 million', 'Central African CFA franc', 'French, English', 'It is often called "Africa in miniature" due to its diversity.', 'CMR', 'Crude Oil', '🇨🇲'],
  ['Canada', ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa'], 'North America', '39 million', 'Canadian dollar', 'English, French', 'It has the longest coastline in the world.', 'CAN', 'Crude Oil', '🇨🇦'],
  ['Cayman Islands', ['George Town', 'West Bay', 'Bodden Town'], 'North America', '68,000', 'Cayman Islands dollar', 'English', 'It is a major world offshore financial center.', 'CYM', 'Financial Services', '🇰🇾'],
  ['Central African Republic', ['Bangui', 'Bimbo', 'Berbérati', 'Carnot'], 'Africa', '5.5 million', 'Central African CFA franc', 'Sango, French', 'It is home to forest elephants and lowland gorillas.', 'CAF', 'Diamonds', '🇨🇫'],
  ['Chad', ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché'], 'Africa', '17 million', 'Central African CFA franc', 'Arabic, French', 'It is home to the Sahara Desert and Lake Chad.', 'TCD', 'Crude Oil', '🇹🇩'],
  ['Chile', ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta'], 'South America', '19.6 million', 'Chilean peso', 'Spanish', 'It is the longest and narrowest country in the world.', 'CHL', 'Copper', '🇨🇱'],
  ['China', ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu'], 'Asia', '1.4 billion', 'Renminbi (Yuan)', 'Standard Chinese', 'It has the largest population in the world (historically).', 'CHN', 'Electronics', '🇨🇳'],
  ['Christmas Island', ['Flying Fish Cove', 'Poon Saan'], 'Oceania', '1,800', 'Australian dollar', 'English', 'It is famous for its annual red crab migration.', 'CXR', 'Phosphate', '🇨🇽'],
  ['Cocos (Keeling) Islands', ['West Island', 'Home Island'], 'Oceania', '600', 'Australian dollar', 'English', 'It consists of two atolls and 27 coral islands.', 'CCK', 'Copra', '🇨🇨'],
  ['Colombia', ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'], 'South America', '52 million', 'Colombian peso', 'Spanish', 'It is the world\'s leading producer of emeralds.', 'COL', 'Crude Oil', '🇨🇴'],
  ['Comoros', ['Moroni', 'Mutsamudu', 'Fomboni'], 'Africa', '836,000', 'Comorian franc', 'Comorian, Arabic, French', 'It is known as the "Perfume Islands" due to ylang-ylang production.', 'COM', 'Cloves/Vanilla', '🇰🇲'],
  ['Congo', ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi'], 'Africa', '6 million', 'Central African CFA franc', 'French', 'It is often referred to as Congo-Brazzaville.', 'COG', 'Crude Oil', '🇨🇬'],
  ['Democratic Republic of the Congo', ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'], 'Africa', '99 million', 'Congolese franc', 'French', 'It is home to the second largest rainforest in the world.', 'COD', 'Cobalt', '🇨🇩'],
  ['Cook Islands', ['Avarua', 'Amuri', 'Omoka'], 'Oceania', '17,000', 'New Zealand dollar', 'English, Cook Islands Māori', 'It has a massive Exclusive Economic Zone of ocean.', 'COK', 'Fish', '🇨🇰'],
  ['Costa Rica', ['San José', 'Alajuela', 'Cartago', 'Heredia'], 'North America', '5.2 million', 'Costa Rican colón', 'Spanish', 'It has no standing army, having abolished it in 1948.', 'CRI', 'Medical Instruments', '🇨🇷'],
  ['Côte d\'Ivoire', ['Abidjan', 'Bouaké', 'Yamoussoukro', 'Daloa'], 'Africa', '28 million', 'West African CFA franc', 'French', 'It is the world\'s largest producer of cocoa beans.', 'CIV', 'Cocoa Beans', '🇨🇮'],
  ['Croatia', ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'], 'Europe', '3.9 million', 'Euro', 'Croatian', 'It invented the necktie (cravat).', 'HRV', 'Refined Petroleum', '🇭🇷'],
  ['Cuba', ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín'], 'North America', '11 million', 'Cuban peso', 'Spanish', 'It is famous for its classic American cars and cigars.', 'CUB', 'Tobacco', '🇨🇺'],
  ['Curaçao', ['Willemstad', 'Sint Michiel', 'Barber'], 'South America', '150,000', 'Netherlands Antillean guilder', 'Dutch, Papiamento, English', 'Its capital features colorful Dutch colonial architecture.', 'CUW', 'Refined Petroleum', '🇨🇼'],
  ['Cyprus', ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'], 'Europe', '1.2 million', 'Euro', 'Greek, Turkish', 'Legend says it is the birthplace of the goddess Aphrodite.', 'CYP', 'Ships', '🇨🇾'],
  ['Czechia', ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec'], 'Europe', '10.5 million', 'Czech koruna', 'Czech', 'It has the most castles per square mile in the world.', 'CZE', 'Cars', '🇨🇿'],
  ['Denmark', ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'], 'Europe', '5.9 million', 'Danish krone', 'Danish', 'It is the home of LEGO.', 'DNK', 'Packaged Medicines', '🇩🇰'],
  ['Djibouti', ['Djibouti City', 'Ali Sabieh', 'Dikhil'], 'Africa', '1.1 million', 'Djiboutian franc', 'French, Arabic', 'It hosts military bases from several world powers due to its strategic location.', 'DJI', 'Re-exports', '🇩🇯'],
  ['Dominica', ['Roseau', 'Portsmouth', 'Marigot'], 'North America', '72,000', 'East Caribbean dollar', 'English', 'It is known as the "Nature Island of the Caribbean".', 'DMA', 'Bananas', '🇩🇲'],
  ['Dominican Republic', ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís'], 'North America', '11 million', 'Dominican peso', 'Spanish', 'It shares the island of Hispaniola with Haiti.', 'DOM', 'Gold', '🇩🇴'],
  ['Ecuador', ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo'], 'South America', '18 million', 'US Dollar', 'Spanish', 'It is named after the Equator, which runs through it.', 'ECU', 'Crude Oil', '🇪🇨'],
  ['Egypt', ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said'], 'Africa', '111 million', 'Egyptian pound', 'Arabic', 'It is home to the Great Pyramids of Giza.', 'EGY', 'Refined Petroleum', '🇪🇬'],
  ['El Salvador', ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel'], 'North America', '6.3 million', 'US Dollar', 'Spanish', 'It is known as the "Land of Volcanoes".', 'SLV', 'Textiles', '🇸🇻'],
  ['Equatorial Guinea', ['Malabo', 'Bata', 'Ebebiyin'], 'Africa', '1.6 million', 'Central African CFA franc', 'Spanish, French, Portuguese', 'It is the only African country where Spanish is an official language.', 'GNQ', 'Crude Oil', '🇬🇶'],
  ['Eritrea', ['Asmara', 'Keren', 'Massawa', 'Assab'], 'Africa', '3.7 million', 'Nakfa', 'Tigrinya, Arabic, English', 'Its capital is known for its well-preserved Art Deco architecture.', 'ERI', 'Zinc Ore', '🇪🇷'],
  ['Estonia', ['Tallinn', 'Tartu', 'Narva', 'Pärnu'], 'Europe', '1.3 million', 'Euro', 'Estonian', 'It is one of the world\'s most digitally advanced societies.', 'EST', 'Broadcasting Equipment', '🇪🇪'],
  ['Eswatini', ['Mbabane', 'Manzini', 'Big Bend'], 'Africa', '1.2 million', 'Lilangeni', 'Swazi, English', 'It is one of the last absolute monarchies in Africa.', 'SWZ', 'Scented Mixtures', '🇸🇿'],
  ['Ethiopia', ['Addis Ababa', 'Dire Dawa', 'Mek\'ele', 'Gondar'], 'Africa', '123 million', 'Birr', 'Amharic', 'It is considered the birthplace of coffee.', 'ETH', 'Coffee', '🇪🇹'],
  ['Falkland Islands (Malvinas)', ['Stanley'], 'South America', '3,700', 'Falkland Islands pound', 'English', 'It has far more sheep than people.', 'FLK', 'Wool', '🇫🇰'],
  ['Faroe Islands', ['Tórshavn', 'Klaksvík'], 'Europe', '53,000', 'Faroese króna', 'Faroese, Danish', 'It is an autonomous territory of Denmark with a strong Viking heritage.', 'FRO', 'Fish', '🇫🇴'],
  ['Fiji', ['Suva', 'Lautoka', 'Nadi', 'Labasa'], 'Oceania', '929,000', 'Fijian dollar', 'English, Fijian', 'It consists of over 300 islands in the South Pacific.', 'FJI', 'Water', '🇫🇯'],
  ['Finland', ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'], 'Europe', '5.5 million', 'Euro', 'Finnish, Swedish', 'It has the most saunas per capita in the world.', 'FIN', 'Paper/Wood', '🇫🇮'],
  ['France', ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice'], 'Europe', '68 million', 'Euro', 'French', 'It is the most visited country in the world.', 'FRA', 'Aircraft', '🇫🇷'],
  ['French Guiana', ['Cayenne', 'Matoury', 'Saint-Laurent-du-Maroni'], 'South America', '300,000', 'Euro', 'French', 'It is home to the Guiana Space Centre, Europe\'s spaceport.', 'GUF', 'Gold', '🇬🇫'],
  ['French Polynesia', ['Papeete', 'Faa\'a', 'Punaauia'], 'Oceania', '280,000', 'CFP franc', 'French', 'It includes the famous island of Bora Bora.', 'PYF', 'Pearls', '🇵🇫'],
  ['French Southern Territories', ['Port-aux-Français'], 'Antarctica', 'No permanent pop.', 'Euro', 'French', 'It is a group of volcanic islands in the southern Indian Ocean.', 'ATF', 'Science', '🇹🇫'],
  ['Gabon', ['Libreville', 'Port-Gentil', 'Franceville'], 'Africa', '2.3 million', 'Central African CFA franc', 'French', 'Over 80% of the country is covered by rainforests.', 'GAB', 'Crude Oil', '🇬🇦'],
  ['Gambia', ['Banjul', 'Serekunda', 'Brikama', 'Bakau'], 'Africa', '2.7 million', 'Dalasi', 'English', 'It is the smallest country on the mainland African continent.', 'GMB', 'Peanuts', '🇬🇲'],
  ['Georgia', ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'], 'Asia', '3.7 million', 'Lari', 'Georgian', 'It is considered the birthplace of wine, making it for 8,000 years.', 'GEO', 'Copper Ore', '🇬🇪'],
  ['Germany', ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne'], 'Europe', '84 million', 'Euro', 'German', 'It has over 1,000 types of sausages.', 'DEU', 'Cars', '🇩🇪'],
  ['Ghana', ['Accra', 'Kumasi', 'Tamale', 'Takoradi'], 'Africa', '33 million', 'Cedi', 'English', 'It was the first sub-Saharan country to gain independence from colonial rule.', 'GHA', 'Gold', '🇬🇭'],
  ['Gibraltar', ['Gibraltar'], 'Europe', '34,000', 'Gibraltar pound', 'English', 'It is famous for the Rock of Gibraltar and its wild monkeys.', 'GIB', 'Online Gaming', '🇬🇮'],
  ['Greece', ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'], 'Europe', '10.4 million', 'Euro', 'Greek', 'It is considered the cradle of Western civilization.', 'GRC', 'Refined Petroleum', '🇬🇷'],
  ['Greenland', ['Nuuk', 'Sisimiut', 'Ilulissat'], 'North America', '56,000', 'Danish krone', 'Greenlandic', 'It is the world\'s largest island.', 'GRL', 'Fish', '🇬🇱'],
  ['Grenada', ['St. George\'s', 'Gouyave', 'Grenville'], 'North America', '125,000', 'East Caribbean dollar', 'English', 'It is known as the "Island of Spice" due to nutmeg production.', 'GRD', 'Nutmeg', '🇬🇩'],
  ['Guadeloupe', ['Les Abymes', 'Baie-Mahault', 'Le Gosier'], 'North America', '384,000', 'Euro', 'French', 'It is an overseas region of France shaped like a butterfly.', 'GLP', 'Bananas', '🇬🇵'],
  ['Guam', ['Dededo', 'Yigo', 'Tamuning', 'Hagåtña'], 'Oceania', '170,000', 'US Dollar', 'English, Chamorro', 'Its slogan is "Where America\'s Day Begins".', 'GUM', 'Tourism/Military', '🇬🇺'],
  ['Guatemala', ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'], 'North America', '18 million', 'Quetzal', 'Spanish', 'It is considered the heart of the Mayan world.', 'GTM', 'Bananas', '🇬🇹'],
  ['Guernsey', ['Saint Peter Port'], 'Europe', '63,000', 'Guernsey pound', 'English', 'It is a Crown Dependency, not part of the UK.', 'GGY', 'Financial Services', '🇬🇬'],
  ['Guinea', ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia'], 'Africa', '14 million', 'Guinean franc', 'French', 'It possesses the world\'s largest reserves of bauxite.', 'GIN', 'Bauxite', '🇬🇳'],
  ['Guinea-Bissau', ['Bissau', 'Bafatá', 'Gabú'], 'Africa', '2 million', 'West African CFA franc', 'Portuguese', 'It is home to the Bijagós Archipelago, a UNESCO biosphere reserve.', 'GNB', 'Cashews', '🇬🇼'],
  ['Guyana', ['Georgetown', 'Linden', 'New Amsterdam'], 'South America', '808,000', 'Guyanese dollar', 'English', 'It is the only English-speaking country in South America.', 'GUY', 'Crude Oil', '🇬🇾'],
  ['Haiti', ['Port-au-Prince', 'Carrefour', 'Delmas', 'Cap-Haïtien'], 'North America', '11.5 million', 'Gourde', 'Haitian Creole, French', 'It was the first independent black republic in the world.', 'HTI', 'Textiles', '🇭🇹'],
  ['Heard Island and McDonald Islands', [], 'Antarctica', '0', 'Australian dollar', 'English', 'It contains Australia\'s only active volcanoes.', 'HMD', 'None', '🇭🇲'],
  ['Holy See', ['Vatican City'], 'Europe', '800', 'Euro', 'Latin, Italian', 'It is the smallest country in the world by both area and population.', 'VAT', 'Tourism', '🇻🇦'],
  ['Honduras', ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'], 'North America', '10 million', 'Lempira', 'Spanish', 'It was the original "Banana Republic".', 'HND', 'Textiles', '🇭🇳'],
  ['Hong Kong', ['Kowloon', 'Victoria City', 'Sha Tin', 'Tuen Mun'], 'Asia', '7.4 million', 'Hong Kong dollar', 'Chinese, English', 'It has the most skyscrapers of any city in the world.', 'HKG', 'Gold', '🇭🇰'],
  ['Hungary', ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'], 'Europe', '9.7 million', 'Forint', 'Hungarian', 'It is known for its thermal baths and spas.', 'HUN', 'Cars', '🇭🇺'],
  ['Iceland', ['Reykjavík', 'Kópavogur', 'Hafnarfjörður'], 'Europe', '376,000', 'Icelandic króna', 'Icelandic', 'It uses almost 100% renewable energy for electricity.', 'ISL', 'Fish', '🇮🇸'],
  ['India', ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata'], 'Asia', '1.4 billion', 'Indian rupee', 'Hindi, English', 'It gave the world the number zero.', 'IND', 'Refined Petroleum', '🇮🇳'],
  ['Indonesia', ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang'], 'Asia', '275 million', 'Indonesian rupiah', 'Indonesian', 'It is the world\'s largest archipelago country.', 'IDN', 'Coal', '🇮🇩'],
  ['Iran', ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz'], 'Asia', '88 million', 'Iranian rial', 'Persian', 'It is one of the world\'s oldest civilizations, formerly known as Persia.', 'IRN', 'Crude Oil', '🇮🇷'],
  ['Iraq', ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf'], 'Asia', '44 million', 'Iraqi dinar', 'Arabic, Kurdish', 'It corresponds to ancient Mesopotamia, the "Cradle of Civilization".', 'IRQ', 'Crude Oil', '🇮🇶'],
  ['Ireland', ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'], 'Europe', '5 million', 'Euro', 'Irish, English', 'It is known as the "Emerald Isle" due to its greenery.', 'IRL', 'Pharmaceuticals', '🇮🇪'],
  ['Isle of Man', ['Douglas', 'Ramsey', 'Peel'], 'Europe', '84,000', 'Manx pound', 'English, Manx', 'It is famous for the TT motorcycle race.', 'IMN', 'Financial Services', '🇮🇲'],
  ['Israel', ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion'], 'Asia', '9.5 million', 'New Shekel', 'Hebrew', 'It has the highest number of museums per capita.', 'ISR', 'Diamonds', '🇮🇱'],
  ['Italy', ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo'], 'Europe', '59 million', 'Euro', 'Italian', 'It has the most UNESCO World Heritage Sites.', 'ITA', 'Packaged Medicines', '🇮🇹'],
  ['Jamaica', ['Kingston', 'Portmore', 'Spanish Town', 'Montego Bay'], 'North America', '2.8 million', 'Jamaican dollar', 'English', 'It is the birthplace of Reggae music and Bob Marley.', 'JAM', 'Bauxite', '🇯🇲'],
  ['Japan', ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo'], 'Asia', '125 million', 'Japanese yen', 'Japanese', 'It has the highest life expectancy in the world.', 'JPN', 'Cars', '🇯🇵'],
  ['Jersey', ['Saint Helier'], 'Europe', '100,000', 'Jersey pound', 'English', 'It is the largest of the Channel Islands.', 'JEY', 'Financial Services', '🇯🇪'],
  ['Jordan', ['Amman', 'Zarqa', 'Irbid', 'Russeifa'], 'Asia', '11 million', 'Jordanian dinar', 'Arabic', 'It is home to Petra, a city carved into rock.', 'JOR', 'Potash', '🇯🇴'],
  ['Kazakhstan', ['Almaty', 'Astana', 'Shymkent', 'Karaganda'], 'Asia', '19 million', 'Tenge', 'Kazakh, Russian', 'It is the largest landlocked country in the world.', 'KAZ', 'Crude Oil', '🇰🇿'],
  ['Kenya', ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'], 'Africa', '54 million', 'Kenyan shilling', 'Swahili, English', 'It is famous for the Great Migration of wildebeest.', 'KEN', 'Tea', '🇰🇪'],
  ['Kiribati', ['Tarawa', 'Betio', 'Bikenibeu'], 'Oceania', '131,000', 'Australian dollar', 'English, Gilbertese', 'It is the only country situated in all four hemispheres.', 'KIR', 'Fish', '🇰🇮'],
  ['North Korea', ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo'], 'Asia', '26 million', 'North Korean won', 'Korean', 'It has the largest stadium in the world by capacity.', 'PRK', 'Coal', '🇰🇵'],
  ['South Korea', ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon'], 'Asia', '51 million', 'South Korean won', 'Korean', 'It has the fastest internet speeds in the world.', 'KOR', 'Integrated Circuits', '🇰🇷'],
  ['Kuwait', ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Salmiya'], 'Asia', '4.2 million', 'Kuwaiti dinar', 'Arabic', 'Its currency is the highest valued in the world.', 'KWT', 'Crude Oil', '🇰🇼'],
  ['Kyrgyzstan', ['Bishkek', 'Osh', 'Jalal-Abad'], 'Asia', '6.6 million', 'Som', 'Kyrgyz, Russian', 'It is incredibly mountainous, dominated by the Tian Shan.', 'KGZ', 'Gold', '🇰🇬'],
  ['Laos', ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'], 'Asia', '7.5 million', 'Kip', 'Lao', 'It is the most heavily bombed country in history per capita.', 'LAO', 'Electricity', '🇱🇦'],
  ['Latvia', ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'], 'Europe', '1.9 million', 'Euro', 'Latvian', 'It has one of the widest waterfalls in Europe, Ventas Rumba.', 'LVA', 'Wood', '🇱🇻'],
  ['Lebanon', ['Beirut', 'Tripoli', 'Sidon', 'Tyre'], 'Asia', '5.5 million', 'Lebanese pound', 'Arabic', 'It is the only Middle Eastern country without a desert.', 'LBN', 'Gold', '🇱🇧'],
  ['Lesotho', ['Maseru', 'Teyateyaneng', 'Mafeteng'], 'Africa', '2.3 million', 'Loti', 'Sotho, English', 'It is the only independent state entirely above 1,000m in elevation.', 'LSO', 'Diamonds', '🇱🇸'],
  ['Liberia', ['Monrovia', 'Gbarnga', 'Buchanan', 'Ganta'], 'Africa', '5.3 million', 'Liberian dollar', 'English', 'It was founded by freed slaves from the United States.', 'LBR', 'Gold/Rubber', '🇱🇷'],
  ['Libya', ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'], 'Africa', '6.8 million', 'Libyan dinar', 'Arabic', 'It was home to the ancient city of Leptis Magna.', 'LBY', 'Crude Oil', '🇱🇾'],
  ['Liechtenstein', ['Vaduz', 'Schaan', 'Triesen'], 'Europe', '39,000', 'Swiss franc', 'German', 'It is one of only two doubly landlocked countries.', 'LIE', 'Specialized Machinery', '🇱🇮'],
  ['Lithuania', ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'], 'Europe', '2.8 million', 'Euro', 'Lithuanian', 'It was the first Soviet republic to declare independence.', 'LTU', 'Refined Petroleum', '🇱🇹'],
  ['Luxembourg', ['Luxembourg City', 'Esch-sur-Alzette', 'Dudelange'], 'Europe', '650,000', 'Euro', 'Luxembourgish, French, German', 'It has the highest GDP per capita in the world.', 'LUX', 'Iron/Steel', '🇱🇺'],
  ['Macao', ['Macau'], 'Asia', '680,000', 'Pataca', 'Chinese, Portuguese', 'It is known as the "Las Vegas of Asia".', 'MAC', 'Gambling/Tourism', '🇲🇴'],
  ['Madagascar', ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'], 'Africa', '29 million', 'Ariary', 'Malagasy, French', '90% of its wildlife is found nowhere else on Earth.', 'MDG', 'Vanilla', '🇲🇬'],
  ['Malawi', ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'], 'Africa', '20 million', 'Malawian kwacha', 'English, Chewa', 'It is nicknamed "The Warm Heart of Africa".', 'MWI', 'Tobacco', '🇲🇼'],
  ['Malaysia', ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Johor Bahru'], 'Asia', '33 million', 'Ringgit', 'Malay', 'It is home to the Petronas Towers, once the world\'s tallest buildings.', 'MYS', 'Integrated Circuits', '🇲🇾'],
  ['Maldives', ['Malé', 'Addu City', 'Fuvahmulah'], 'Asia', '540,000', 'Rufiyaa', 'Dhivehi', 'It is the lowest country in the world by average elevation.', 'MDV', 'Fish', '🇲🇻'],
  ['Mali', ['Bamako', 'Sikasso', 'Kalabancoro', 'Koutiala'], 'Africa', '22 million', 'West African CFA franc', 'Bambara, French', 'It was home to the wealthy Mansa Musa and Timbuktu.', 'MLI', 'Gold', '🇲🇱'],
  ['Malta', ['Valletta', 'Birkirkara', 'Mosta', 'St. Paul\'s Bay'], 'Europe', '530,000', 'Euro', 'Maltese, English', 'Its capital, Valletta, is a UNESCO World Heritage site.', 'MLT', 'Integrated Circuits', '🇲🇹'],
  ['Marshall Islands', ['Majuro', 'Ebeye'], 'Oceania', '41,000', 'US Dollar', 'English, Marshallese', 'It is composed entirely of coral atolls.', 'MHL', 'Ships', '🇲🇭'],
  ['Martinique', ['Fort-de-France', 'Le Lamentin', 'Le Robert'], 'North America', '375,000', 'Euro', 'French', 'It is known as the "Isle of Flowers".', 'MTQ', 'Refined Petroleum', '🇲🇶'],
  ['Mauritania', ['Nouakchott', 'Nouadhibou', 'Kiffa'], 'Africa', '4.7 million', 'Ouguiya', 'Arabic', 'It has the Eye of the Sahara, a massive circular geological feature.', 'MRT', 'Iron Ore', '🇲🇷'],
  ['Mauritius', ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix'], 'Africa', '1.3 million', 'Mauritian rupee', 'English, French', 'It was the only known home of the Dodo bird.', 'MUS', 'Fish', '🇲🇺'],
  ['Mayotte', ['Mamoudzou', 'Koungou'], 'Africa', '326,000', 'Euro', 'French', 'It is an overseas department of France in the Indian Ocean.', 'MYT', 'Perfume Plants', '🇾🇹'],
  ['Mexico', ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana'], 'North America', '127 million', 'Mexican peso', 'Spanish', 'It introduced chocolate, corn, and chilies to the world.', 'MEX', 'Cars', '🇲🇽'],
  ['Micronesia', ['Palikir', 'Weno', 'Colonia'], 'Oceania', '115,000', 'US Dollar', 'English', 'It is spread across the western Pacific Ocean comprising 607 islands.', 'FSM', 'Fish', '🇫🇲'],
  ['Moldova', ['Chisinau', 'Balti', 'Tiraspol', 'Bender'], 'Europe', '2.5 million', 'Moldovan leu', 'Romanian', 'It has the largest wine cellar in the world by number of bottles.', 'MDA', 'Corn/Wine', '🇲🇩'],
  ['Monaco', ['Monaco', 'Monte Carlo', 'La Condamine'], 'Europe', '36,000', 'Euro', 'French', 'It is the second smallest country in the world.', 'MCO', 'Cosmetics', '🇲🇨'],
  ['Mongolia', ['Ulaanbaatar', 'Erdenet', 'Darkhan'], 'Asia', '3.4 million', 'Tögrög', 'Mongolian', 'It is the most sparsely populated sovereign nation.', 'MNG', 'Copper Ore', '🇲🇳'],
  ['Montenegro', ['Podgorica', 'Nikšić', 'Herceg Novi'], 'Europe', '619,000', 'Euro', 'Montenegrin', 'Its name means "Black Mountain".', 'MNE', 'Aluminum', '🇲🇪'],
  ['Montserrat', ['Brades', 'Plymouth'], 'North America', '4,300', 'East Caribbean dollar', 'English', 'Its former capital was buried by a volcanic eruption.', 'MSR', 'Sand', '🇲🇸'],
  ['Morocco', ['Casablanca', 'Rabat', 'Fes', 'Tangier', 'Marrakesh'], 'Africa', '37 million', 'Moroccan dirham', 'Arabic, Berber', 'It is home to the oldest university in the world, Al Quaraouiyine.', 'MAR', 'Phosphates/Fertilizers', '🇲🇦'],
  ['Mozambique', ['Maputo', 'Matola', 'Beira', 'Nampula'], 'Africa', '32 million', 'Metical', 'Portuguese', 'Its flag is the only one to feature a modern assault rifle.', 'MOZ', 'Coal', '🇲🇿'],
  ['Myanmar', ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine'], 'Asia', '54 million', 'Kyat', 'Burmese', 'It is known as the "Land of Golden Pagodas".', 'MMR', 'Natural Gas', '🇲🇲'],
  ['Namibia', ['Windhoek', 'Rundu', 'Walvis Bay'], 'Africa', '2.5 million', 'Namibian dollar', 'English', 'It has the oldest desert in the world, the Namib.', 'NAM', 'Diamonds', '🇳🇦'],
  ['Nauru', ['Yaren', 'Denigomodu', 'Meneng'], 'Oceania', '12,000', 'Australian dollar', 'Nauruan, English', 'It is the smallest island nation and has no official capital.', 'NRU', 'Fish', '🇳🇷'],
  ['Nepal', ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar'], 'Asia', '30 million', 'Nepalese rupee', 'Nepali', 'It is the only country with a non-rectangular flag.', 'NPL', 'Carpets', '🇳🇵'],
  ['Netherlands', ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'], 'Europe', '17.7 million', 'Euro', 'Dutch', 'About 26% of its land is below sea level.', 'NLD', 'Refined Petroleum', '🇳🇱'],
  ['New Caledonia', ['Nouméa', 'Dumbéa', 'Le Mont-Dore'], 'Oceania', '290,000', 'CFP franc', 'French', 'It has the largest lagoon in the world.', 'NCL', 'Nickel', '🇳🇨'],
  ['New Zealand', ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'], 'Oceania', '5.1 million', 'New Zealand dollar', 'English, Māori', 'It was the filming location for The Lord of the Rings.', 'NZL', 'Dairy/Lamb', '🇳🇳'],
  ['Nicaragua', ['Managua', 'León', 'Masaya', 'Matagalpa'], 'North America', '6.9 million', 'Córdoba', 'Spanish', 'It has the largest freshwater lake in Central America.', 'NIC', 'Coffee', '🇳🇮'],
  ['Niger', ['Niamey', 'Maradi', 'Zinder', 'Tahoua'], 'Africa', '26 million', 'West African CFA franc', 'French', 'It is named after the Niger River.', 'NER', 'Uranium', '🇳🇪'],
  ['Nigeria', ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt'], 'Africa', '218 million', 'Naira', 'English', 'It is the most populous country in Africa.', 'NGA', 'Crude Oil', '🇳🇬'],
  ['Niue', ['Alofi'], 'Oceania', '1,600', 'New Zealand dollar', 'Niuean, English', 'It is the world\'s first "Dark Sky Nation".', 'NIU', 'Fish', '🇳🇺'],
  ['Norfolk Island', ['Kingston', 'Burnt Pine'], 'Oceania', '2,000', 'Australian dollar', 'English, Norfuk', 'It is known for its iconic pine trees.', 'NFK', 'Seeds', '🇳🇫'],
  ['North Macedonia', ['Skopje', 'Bitola', 'Kumanovo', 'Prilep'], 'Europe', '1.8 million', 'Denar', 'Macedonian', 'It is the birthplace of Mother Teresa.', 'MKD', 'Chemicals', '🇲🇰'],
  ['Northern Mariana Islands', ['Saipan', 'Tinian', 'Rota'], 'Oceania', '49,000', 'US Dollar', 'English, Chamorro', 'It includes the Mariana Trench, the deepest point on Earth.', 'MNP', 'Tourism', '🇲🇵'],
  ['Norway', ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'], 'Europe', '5.4 million', 'Norwegian krone', 'Norwegian', 'It knighted a penguin named Sir Nils Olav.', 'NOR', 'Crude Oil/Gas', '🇳🇴'],
  ['Oman', ['Muscat', 'Seeb', 'Salalah', 'Bawshar'], 'Asia', '4.5 million', 'Omani rial', 'Arabic', 'It is the oldest independent state in the Arab world.', 'OMN', 'Crude Oil', '🇴🇲'],
  ['Pakistan', ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi'], 'Asia', '235 million', 'Pakistani rupee', 'Urdu, English', 'It has the second highest mountain, K2.', 'PAK', 'Textiles', '🇵🇰'],
  ['Palau', ['Ngerulmud', 'Koror', 'Airai'], 'Oceania', '18,000', 'US Dollar', 'Palauan, English', 'It created the world\'s first shark sanctuary.', 'PLW', 'Fish', '🇵🇼'],
  ['Palestine', ['Gaza City', 'East Jerusalem', 'Hebron', 'Nablus', 'Ramallah'], 'Asia', '5.3 million', 'Shekel, Dinar', 'Arabic', 'It contains Jericho, one of the oldest inhabited cities.', 'PSE', 'Stone/Olives', '🇵🇸'],
  ['Panama', ['Panama City', 'San Miguelito', 'Tocumen', 'David'], 'North America', '4.4 million', 'Balboa, US Dollar', 'Spanish', 'It is the only place where you can see the sun rise on the Pacific and set on the Atlantic.', 'PAN', 'Refined Petroleum', '🇵🇦'],
  ['Papua New Guinea', ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen'], 'Oceania', '10 million', 'Kina', 'English, Tok Pisin', 'It has over 800 distinct languages spoken.', 'PNG', 'Gold/LNG', '🇵🇬'],
  ['Paraguay', ['Asunción', 'Ciudad del Este', 'Luque', 'San Lorenzo'], 'South America', '6.7 million', 'Guaraní', 'Spanish, Guaraní', 'It generates almost 100% of its electricity from hydropower.', 'PRY', 'Electricity', '🇵🇾'],
  ['Peru', ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco'], 'South America', '34 million', 'Sol', 'Spanish', 'It is home to Machu Picchu, the Lost City of the Incas.', 'PER', 'Copper Ore', '🇵🇪'],
  ['Philippines', ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga City'], 'Asia', '115 million', 'Philippine peso', 'Filipino, English', 'It is composed of over 7,600 islands.', 'PHL', 'Integrated Circuits', '🇵🇭'],
  ['Pitcairn', ['Adamstown'], 'Oceania', '50', 'New Zealand dollar', 'English, Pitkern', 'It is inhabited by descendants of the HMS Bounty mutineers.', 'PCN', 'Honey', '🇵🇳'],
  ['Poland', ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'], 'Europe', '37 million', 'Złoty', 'Polish', 'It is home to the world\'s biggest castle by land area (Malbork).', 'POL', 'Vehicle Parts', '🇵🇱'],
  ['Portugal', ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora'], 'Europe', '10.3 million', 'Euro', 'Portuguese', 'It is the oldest nation-state on the Iberian Peninsula.', 'PRT', 'Cars', '🇵🇹'],
  ['Puerto Rico', ['San Juan', 'Bayamón', 'Carolina', 'Ponce'], 'North America', '3.2 million', 'US Dollar', 'Spanish, English', 'It is home to the Coquí frog, a national symbol.', 'PRI', 'Pharmaceuticals', '🇵🇷'],
  ['Qatar', ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'], 'Asia', '2.7 million', 'Qatari riyal', 'Arabic', 'It has the highest GDP per capita in the world (PPP).', 'QAT', 'Natural Gas', '🇶🇦'],
  ['Romania', ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași'], 'Europe', '19 million', 'Romanian leu', 'Romanian', 'It is home to the legend of Dracula (Transylvania).', 'ROU', 'Vehicle Parts', '🇷🇴'],
  ['Russia', ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan'], 'Europe/Asia', '144 million', 'Russian ruble', 'Russian', 'It is the largest country in the world by land area.', 'RUS', 'Oil/Gas', '🇷🇺'],
  ['Rwanda', ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'], 'Africa', '13.7 million', 'Rwandan franc', 'Kinyarwanda, English, French', 'It is known as the "Land of a Thousand Hills".', 'RWA', 'Gold', '🇷🇼'],
  ['Réunion', ['Saint-Denis', 'Saint-Paul', 'Saint-Pierre'], 'Africa', '860,000', 'Euro', 'French', 'It holds the world record for most rainfall in 12/24 hours.', 'REU', 'Sugar', '🇷🇪'],
  ['Saint Barthélemy', ['Gustavia'], 'North America', '10,000', 'Euro', 'French', 'It is a luxury destination often called St. Barts.', 'BLM', 'Tourism', '🇧🇱'],
  ['Saint Helena, Ascension and Tristan da Cunha', ['Jamestown', 'Georgetown', 'Edinburgh of the Seven Seas'], 'Africa', '5,000', 'Saint Helena pound', 'English', 'It was the place of Napoleon Bonaparte\'s exile.', 'SHN', 'Fish', '🇸🇭'],
  ['Saint Kitts and Nevis', ['Basseterre', 'Charlestown'], 'North America', '47,000', 'East Caribbean dollar', 'English', 'It is the smallest sovereign state in the Western Hemisphere.', 'KNA', 'Broadcasting Equipment', '🇰🇳'],
  ['Saint Lucia', ['Castries', 'Gros Islet', 'Vieux Fort'], 'North America', '180,000', 'East Caribbean dollar', 'English', 'It is the only country named after a woman.', 'LCA', 'Refined Petroleum', '🇱🇨'],
  ['Saint Martin (French part)', ['Marigot'], 'North America', '32,000', 'Euro', 'French', 'It shares an island with Sint Maarten (Netherlands).', 'MAF', 'Tourism', '🇲🇫'],
  ['Saint Pierre and Miquelon', ['Saint-Pierre', 'Miquelon-Langlade'], 'North America', '6,000', 'Euro', 'French', 'It is the last remnant of New France in North America.', 'SPM', 'Fish', '🇵🇲'],
  ['Saint Vincent and the Grenadines', ['Kingstown', 'Georgetown'], 'North America', '104,000', 'East Caribbean dollar', 'English', 'It was a major filming location for Pirates of the Caribbean.', 'VCT', 'Pleasure Boats', '🇻🇨'],
  ['Samoa', ['Apia', 'Vaitele', 'Faleasiu'], 'Oceania', '220,000', 'Tālā', 'Samoan, English', 'In 2011, it skipped a day to switch time zones.', 'WSM', 'Insulated Wire', '🇼🇸'],
  ['San Marino', ['San Marino', 'Serravalle', 'Borgo Maggiore'], 'Europe', '33,000', 'Euro', 'Italian', 'It is the world\'s oldest surviving republic.', 'SMR', 'Washing Machines', '🇸🇲'],
  ['Sao Tome and Principe', ['São Tomé', 'Trindade'], 'Africa', '227,000', 'Dobra', 'Portuguese', 'It was one of the first countries to grow cocoa.', 'STP', 'Cocoa Beans', '🇸🇹'],
  ['Saudi Arabia', ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'], 'Asia', '36 million', 'Saudi riyal', 'Arabic', 'It is the largest country in the world without a river.', 'SAU', 'Crude Oil', '🇸🇦'],
  ['Senegal', ['Dakar', 'Touba', 'Thiès', 'Rufisque'], 'Africa', '17 million', 'West African CFA franc', 'French, Wolof', 'It is the westernmost point of the African mainland.', 'SEN', 'Fish/Gold', '🇸🇳'],
  ['Serbia', ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'], 'Europe', '6.8 million', 'Serbian dinar', 'Serbian', 'It is one of the world\'s leading raspberry exporters.', 'SRB', 'Insulated Wire', '🇷🇸'],
  ['Seychelles', ['Victoria', 'Anse Etoile'], 'Africa', '100,000', 'Seychellois rupee', 'Seychellois Creole, English, French', 'It is home to the Coco de Mer, the largest seed in the world.', 'SYC', 'Boats', '🇸🇨'],
  ['Sierra Leone', ['Freetown', 'Bo', 'Kenema', 'Makeni'], 'Africa', '8.6 million', 'Leone', 'English', 'Its name means "Lion Mountains".', 'SLE', 'Titanium Ore', '🇸🇱'],
  ['Singapore', ['Singapore'], 'Asia', '5.6 million', 'Singapore dollar', 'English, Malay, Chinese', 'It is a city-state and the only island city-country.', 'SGP', 'Refined Petroleum', '🇸🇬'],
  ['Sint Maarten (Dutch part)', ['Philipsburg', 'Lower Prince\'s Quarter'], 'North America', '44,000', 'Neth. Antillean guilder', 'Dutch, English', 'Its airport is famous for planes flying low over the beach.', 'SXM', 'Tourism', '🇸🇽'],
  ['Slovakia', ['Bratislava', 'Košice', 'Prešov', 'Žilina'], 'Europe', '5.4 million', 'Euro', 'Slovak', 'It has the highest number of castles and chateaux per capita.', 'SVK', 'Cars', '🇸🇰'],
  ['Slovenia', ['Ljubljana', 'Maribor', 'Celje', 'Kranj'], 'Europe', '2.1 million', 'Euro', 'Slovene', 'It is the only country with "LOVE" in its name.', 'SVN', 'Packaged Medicines', '🇸🇮'],
  ['Solomon Islands', ['Honiara', 'Gizo', 'Auki'], 'Oceania', '724,000', 'Solomon Islands dollar', 'English', 'It was a major theatre of the Pacific War in WWII.', 'SLB', 'Timber', '🇸🇧'],
  ['Somalia', ['Mogadishu', 'Hargeisa', 'Bosaso', 'Galkayo'], 'Africa', '17 million', 'Somali shilling', 'Somali, Arabic', 'It has the longest coastline on mainland Africa.', 'SOM', 'Livestock', '🇸🇴'],
  ['South Africa', ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Gqeberha'], 'Africa', '60 million', 'Rand', 'Zulu, Xhosa, Afrikaans, English', 'It has three capital cities.', 'ZAF', 'Platinum/Gold', '🇿🇦'],
  ['South Georgia and the South Sandwich Islands', ['King Edward Point', 'Grytviken'], 'Antarctica', 'No permanent pop.', 'Pound sterling', 'English', 'It is the final resting place of explorer Ernest Shackleton.', 'SGS', 'Fish', '🇬🇸'],
  ['South Sudan', ['Juba', 'Malakal', 'Wau', 'Yambio'], 'Africa', '11 million', 'South Sudanese pound', 'English', 'It is the world\'s youngest sovereign nation (2011).', 'SSD', 'Crude Oil', '🇸🇸'],
  ['Spain', ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza'], 'Europe', '47 million', 'Euro', 'Spanish', 'It is the world\'s largest producer of olive oil.', 'ESP', 'Cars', '🇪🇸'],
  ['Sri Lanka', ['Colombo', 'Kandy', 'Galle', 'Jaffna'], 'Asia', '22 million', 'Sri Lankan rupee', 'Sinhala, Tamil', 'It was known as Ceylon until 1972.', 'LKA', 'Tea', '🇱🇰'],
  ['Sudan', ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala'], 'Africa', '46 million', 'Sudanese pound', 'Arabic, English', 'It has more pyramids than Egypt.', 'SDN', 'Gold', '🇸🇩'],
  ['Suriname', ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'], 'South America', '618,000', 'Surinamese dollar', 'Dutch', 'It is the most forested country in the world.', 'SUR', 'Gold', '🇸🇷'],
  ['Svalbard and Jan Mayen', ['Longyearbyen', 'Barentsburg'], 'Europe', '2,500', 'Norwegian krone', 'Norwegian', 'It houses the Global Seed Vault.', 'SJM', 'Coal', '🇸🇯'],
  ['Sweden', ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'], 'Europe', '10.5 million', 'Swedish krona', 'Swedish', 'It imports waste from other countries to power its energy plants.', 'SWE', 'Cars', '🇸🇪'],
  ['Switzerland', ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'], 'Europe', '8.7 million', 'Swiss franc', 'German, French, Italian', 'It has not been at war since 1815.', 'CHE', 'Gold', '🇨🇭'],
  ['Syria', ['Damascus', 'Aleppo', 'Homs', 'Latakia'], 'Asia', '22 million', 'Syrian pound', 'Arabic', 'Damascus is widely believed to be the oldest continuously inhabited city.', 'SYR', 'Olive Oil', '🇸🇾'],
  ['Taiwan', ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'], 'Asia', '23 million', 'New Taiwan dollar', 'Mandarin', 'It is a global leader in semiconductor manufacturing.', 'TWN', 'Semiconductors', '🇹🇼'],
  ['Tajikistan', ['Dushanbe', 'Khujand', 'Bokhtar', 'Kulob'], 'Asia', '10 million', 'Somoni', 'Tajik', 'More than 90% of the country is mountainous.', 'TJK', 'Gold', '🇹🇯'],
  ['Tanzania', ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Zanzibar City'], 'Africa', '65 million', 'Tanzanian shilling', 'Swahili, English', 'It is home to Mount Kilimanjaro, Africa\'s highest peak.', 'TZA', 'Gold', '🇹🇿'],
  ['Thailand', ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Nonthaburi'], 'Asia', '71 million', 'Baht', 'Thai', 'It is the only Southeast Asian country never colonized by Europe.', 'THA', 'Computer Parts', '🇹🇭'],
  ['Timor-Leste', ['Dili', 'Baucau', 'Maliana'], 'Asia', '1.3 million', 'US Dollar', 'Tetum, Portuguese', 'It was the first new sovereign state of the 21st century.', 'TLS', 'Crude Oil', '🇹🇱'],
  ['Togo', ['Lomé', 'Sokodé', 'Kara', 'Kpalimé'], 'Africa', '8.8 million', 'West African CFA franc', 'French', 'Its capital, Lomé, is known for its grand markets.', 'TGO', 'Phosphates', '🇹🇬'],
  ['Tokelau', ['Atafu', 'Nukunonu', 'Fakaofo'], 'Oceania', '1,500', 'New Zealand dollar', 'Tokelauan, English', 'It became the world\'s first 100% solar-powered nation.', 'TKL', 'Stamps', '🇹🇰'],
  ['Tonga', ['Nuku\'alofa', 'Neiafu', 'Haveluloto'], 'Oceania', '106,000', 'Pa\'anga', 'Tongan, English', 'It is the only Pacific monarchy to retain its independence.', 'TON', 'Squash', '🇹🇴'],
  ['Trinidad and Tobago', ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima'], 'North America', '1.5 million', 'Trinidad and Tobago dollar', 'English', 'It is the birthplace of the steelpan drum.', 'TTO', 'Natural Gas', '🇹🇹'],
  ['Tunisia', ['Tunis', 'Sfax', 'Sousse', 'Kairouan'], 'Africa', '12 million', 'Tunisian dinar', 'Arabic', 'It was the location of the ancient city of Carthage.', 'TUN', 'Insulated Wire', '🇹🇳'],
  ['Turkey', ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana'], 'Asia/Europe', '85 million', 'Turkish lira', 'Turkish', 'Istanbul sits on two continents.', 'TUR', 'Cars', '🇹🇷'],
  ['Turkmenistan', ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary'], 'Asia', '6 million', 'Turkmen manat', 'Turkmen', 'It is home to the "Gates of Hell" gas crater.', 'TKM', 'Natural Gas', '🇹🇲'],
  ['Turks and Caicos Islands', ['Cockburn Town', 'Providenciales'], 'North America', '45,000', 'US Dollar', 'English', 'It has the third largest barrier reef system in the world.', 'TCA', 'Lobster', '🇹🇨'],
  ['Tuvalu', ['Funafuti'], 'Oceania', '11,000', 'Australian dollar', 'Tuvaluan, English', 'It receives income from the .tv internet domain.', 'TUV', 'Fish', '🇹🇻'],
  ['Uganda', ['Kampala', 'Nansana', 'Kira', 'Mbarara'], 'Africa', '47 million', 'Ugandan shilling', 'English, Swahili', 'It is home to almost half of the world\'s mountain gorillas.', 'UGA', 'Gold', '🇺🇬'],
  ['Ukraine', ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv'], 'Europe', '38 million', 'Hryvnia', 'Ukrainian', 'It is often called the "Breadbasket of Europe".', 'UKR', 'Grain/Steel', '🇺🇦'],
  ['United Arab Emirates', ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'], 'Asia', '9.4 million', 'UAE dirham', 'Arabic', 'It is home to the world\'s tallest building, the Burj Khalifa.', 'ARE', 'Crude Oil', '🇦🇪'],
  ['United Kingdom', ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Edinburgh', 'Liverpool'], 'Europe', '67 million', 'Pound sterling', 'English', 'It has no written constitution.', 'GBR', 'Cars', '🇬🇧'],
  ['United States Minor Outlying Islands', [], 'Oceania', '0', 'US Dollar', 'English', 'It consists mostly of uninhabited wildlife refuges.', 'UMI', 'None', '🇺🇲'],
  ['United States', ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'], 'North America', '333 million', 'US Dollar', 'English', 'It has the world\'s largest economy.', 'USA', 'Refined Petroleum', '🇺🇸'],
  ['Uruguay', ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú'], 'South America', '3.4 million', 'Uruguayan peso', 'Spanish', 'It won the first ever FIFA World Cup in 1930.', 'URY', 'Beef', '🇺🇾'],
  ['Uzbekistan', ['Tashkent', 'Samarkand', 'Namangan', 'Andijan'], 'Asia', '35 million', 'Uzbek som', 'Uzbek', 'It is one of two doubly landlocked countries in the world.', 'UZB', 'Gold', '🇺🇿'],
  ['Vanuatu', ['Port Vila', 'Luganville'], 'Oceania', '326,000', 'Vatu', 'Bislama, English, French', 'It is the birthplace of bungee jumping (land diving).', 'VUT', 'Fish', '🇻🇺'],
  ['Venezuela', ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'], 'South America', '28 million', 'Bolívar', 'Spanish', 'It has the world\'s highest uninterrupted waterfall, Angel Falls.', 'VEN', 'Crude Oil', '🇻🇪'],
  ['Vietnam', ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho'], 'Asia', '98 million', 'Vietnamese dong', 'Vietnamese', 'It is the world\'s second largest coffee exporter.', 'VNM', 'Electronics', '🇻🇳'],
  ['Virgin Islands (British)', ['Road Town', 'Spanish Town'], 'North America', '31,000', 'US Dollar', 'English', 'It is a popular yachting destination.', 'VGB', 'Rum', '🇻🇬'],
  ['Virgin Islands (U.S.)', ['Charlotte Amalie', 'Christiansted', 'Frederiksted'], 'North America', '105,000', 'US Dollar', 'English', 'It is the only US territory where cars drive on the left.', 'VIR', 'Refined Petroleum', '🇻🇮'],
  ['Wallis and Futuna', ['Mata-Utu', 'Alele', 'Falaleu'], 'Oceania', '11,000', 'CFP franc', 'French', 'It has three traditional kings recognized by France.', 'WLF', 'Coconuts', '🇼🇫'],
  ['Western Sahara', ['Laayoune', 'Dakhla', 'Smara'], 'Africa', '600,000', 'Moroccan dirham', 'Arabic', 'It is a disputed territory with a phosphate-rich desert.', 'ESH', 'Phosphates', '🇪🇭'],
  ['Yemen', ['Sana\'a', 'Aden', 'Taiz', 'Hodeidah'], 'Asia', '33 million', 'Yemeni rial', 'Arabic', 'It is home to the "Manhattan of the Desert" (Shibam).', 'YEM', 'Crude Oil', '🇾🇪'],
  ['Zambia', ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe'], 'Africa', '20 million', 'Zambian kwacha', 'English', 'It shares Victoria Falls with Zimbabwe.', 'ZMB', 'Copper', '🇿🇲'],
  ['Zimbabwe', ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'], 'Africa', '16 million', 'US Dollar (mostly)', 'Shona, Ndebele, English', 'It has one of the largest elephant populations in the world.', 'ZWE', 'Gold', '🇿🇼'],
  ['Åland Islands', ['Mariehamn'], 'Europe', '30,000', 'Euro', 'Swedish', 'It is a demilitarized zone belonging to Finland.', 'ALA', 'Ships', '🇦🇽']
];

// Helper function to convert raw data into the final object structure
const COUNTRIES_AND_CITIES = rawCountryData.map(item => ({
  country: item[0],
  cities: item[1],
  region: item[2],
  population: item[3],
  currency: item[4],
  language: item[5],
  fun_fact: item[6],
  iso_code: item[7],   // New Field
  main_export: item[8], // New Field
  flag: item[9]        // New Field
}));

module.exports = { COUNTRIES_AND_CITIES };